"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const FAQ = [
  {
    q: "Is this a live product or a demonstration?",
    a: "This is a demonstration build. It runs entirely on seeded fictional data stored locally, so every screen, form, workflow and report is interactive without needing a real hospital, doctor or client account. The same frontend is designed to run against a PostgreSQL/Prisma backend later without rewriting the UI.",
  },
  {
    q: "Where does the data come from, and is any of it real?",
    a: "Every hospital, doctor, candidate, medical registration number, contract, bank reference, invoice and payment in this environment is generated by a deterministic seeder and is fictional. No real person, credential, patient or financial record is present, and none of it should be treated as verified medical credential data.",
  },
  {
    q: "Do payments, payroll disbursements or messages actually leave the system?",
    a: "No. Payment receipts, expense reimbursements, offer letters and communication logs are recorded as simulated workflows. The platform never initiates a bank transfer, never calls an SMS or email gateway, and never contacts a payroll provider. Records are clearly labelled as simulated so a reviewer is never misled.",
  },
  {
    q: "How does role-based access control work?",
    a: "Nine roles are defined with an explicit permission map. Permissions are enforced in the API layer on every request, not just by hiding menu items: a Recruiter calling a payroll endpoint receives a 403 from the server. A role switcher is provided in this demonstration so a reviewer can inspect every permission set without creating multiple accounts. Production deployments disable the switcher.",
  },
  {
    q: "How are statutory payroll components handled?",
    a: "Professional tax, provident fund, ESI, TDS and invoice tax are configurable per salary structure and per invoice, driven by a settings screen with explicit notes. They are illustrative configuration values, not a statement of applicable law or rates, because applicability varies by wage level, establishment and jurisdiction. Confirm requirements with a qualified professional before using the platform for live payroll.",
  },
  {
    q: "Can a doctor be deployed to two hospitals at the same time?",
    a: "No. A doctor may hold multiple historical deployment records, but the allocation and deployment APIs reject a new active or confirmed assignment that overlaps an existing one. The same conflict detection applies to shifts within a day. The check runs on the server, so it holds even for direct API calls.",
  },
  {
    q: "What happens to payroll after it is finalised?",
    a: "A finalised payroll run is locked and its payslips are generated. Editing a locked record is rejected; corrections are made through controlled adjustments in a later period, which keeps the payroll audit trail intact. Finalised run identifiers, totals and approver are recorded in the audit log.",
  },
  {
    q: "How is sensitive data handled?",
    a: "Medical registration numbers, bank details, salary figures and employment records are treated as sensitive. Registration numbers and account numbers are masked in list views, portal roles only see records scoped to their own hospital or their own employee record, and every critical create, update, delete, approval and status change writes an audit entry with the actor, role, timestamp and changed fields.",
  },
];

export function Faq() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <div className="divide-y" style={{ borderColor: "var(--border)" }}>
      {FAQ.map((item, i) => (
        <div key={item.q}>
          <button
            onClick={() => setOpen(open === i ? null : i)}
            aria-expanded={open === i}
            className="flex w-full items-start justify-between gap-4 py-4 text-left ring-focus"
          >
            <span className="text-[15px] font-medium">{item.q}</span>
            <ChevronDown className={cn("mt-0.5 h-5 w-5 shrink-0 text-muted transition-transform", open === i && "rotate-180")} />
          </button>
          {open === i ? (
            <p className="animate-fade-up max-w-3xl pb-5 text-[14px] leading-relaxed text-muted">{item.a}</p>
          ) : null}
        </div>
      ))}
    </div>
  );
}
